# Generated by Django 2.1.4 on 2020-03-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon',
            name='episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toon',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toon',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
