# Generated by Django 2.1.4 on 2020-03-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectoon', '0002_auto_20200320_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WebToon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='toon',
            name='title',
        ),
        migrations.AddField(
            model_name='toon',
            name='webtoon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectoon.WebToon'),
        ),
    ]
