# Generated by Django 2.1.4 on 2020-03-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectoon', '0004_auto_20200320_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtoon',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
