# Generated by Django 2.1.4 on 2020-03-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectoon', '0005_webtoon_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toon',
            name='webtoon',
        ),
        migrations.RemoveField(
            model_name='webtoon',
            name='author',
        ),
        migrations.DeleteModel(
            name='Toon',
        ),
        migrations.DeleteModel(
            name='WebToon',
        ),
    ]
